---
- hosts: all
  remote_user: ansible
  become: yes
  gather_facts: no
  tasks:  
  - name: Install apache
    command: yum install --quiet -y httpd httpd-devel
  - name: Copy configuration files
    command: cp /home/ansible/file.txt /etc/httpd/conf/httpd.conf
    # command: cp /home/ansible/file.txt /etc/httpd/conf/httpd-vhosts.conf
  # - name: Start Apache service
    # command: service httpd start
  # - name: Apache at boot time
    # command: chkconfig httpd on
    
  